
OPENSSL_VERSION_NUMBER = OPENSSL_VERSION_INFO = OPENSSL_VERSION = 1
SSLError = {}
CERT_NONE = CERT_OPTIONAL = CERT_REQUIRED = True
RAND_status = RAND_egd = RAND_add = True
SSL_ERROR_ZERO_RETURN = 1
SSL_ERROR_WANT_READ = 1
SSL_ERROR_WANT_WRITE = 1
SSL_ERROR_WANT_X509_LOOKUP = 1
SSL_ERROR_SYSCALL = 1
SSL_ERROR_SSL = 1
SSL_ERROR_WANT_CONNECT = 1
SSL_ERROR_EOF = 1
SSL_ERROR_INVALID_ERROR_CODE = 1

PROTOCOL_SSLv3 = PROTOCOL_SSLv23 = PROTOCOL_TLSv1 = True
_PROTOCOL_NAMES = {
    PROTOCOL_TLSv1: "TLSv1",
    PROTOCOL_SSLv23: "SSLv23",
    PROTOCOL_SSLv3: "SSLv3",
}
